[package]
name = "rust_fact"
version = "0.1.0"
authors = ["ptliu <ptliu@users.noreply.github.com>"]
edition = "2018"

[dependencies]
sodiumoxide = "0.2.1"
dudect-bencher = "0.4.0"
rand = "0.6.5"
clap = "2.25"
